# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name adjust_for_queue_l
#' @title Adjust admit queue list
#' @description Check how many patients from each facility need to go to the queue.
#' @param patients List of patients at each facility
#' @param q_vec number in queue total
#' @return adjusted queue list.
#' @export
adjust_for_queue_i <- function(num_pat, q_n) {
    .Call(`_abmpack_adjust_for_queue_i`, num_pat, q_n)
}

adjust_for_queue_l <- function(patients, q_vec) {
    .Call(`_abmpack_adjust_for_queue_l`, patients, q_vec)
}

#' @name rcpp_assign_rooms_cpp_seed
#' @title Assign rooms to patients
#' @description Randomly assign patients to hospital rooms with rcpp seed.
#' Designed to deal with one facility at a time.
#' @param pat_risks data frame where each row is a facility and four columns
#' one for each risk level to hold the number of patients at each risk level
#' per hospital
#' @param icu vector of number of icu rooms available at each hospital
#' @param non vector of number of non-icu rooms available at each hospital
#' @param seed seed to be passed in to rcpp
#' @return returns data frame with one column for patient and a second column
#' @export
#' for the room number to which they are assigned.
rcpp_assign_rooms_cpp_seed <- function(pat_risks, icu, non, seed) {
    .Call(`_abmpack_rcpp_assign_rooms_cpp_seed`, pat_risks, icu, non, seed)
}

#' @name get_day_mvts_cpp
#' @title Determine the time/location for each patient's daily movements.
#' @description Check how many patients from each facility need to go to the queue.
#' @param ids vector of patients to get daily movement pattern for
#' @param icu_num vector of equal length to ids with the number of icu movements
#' for each patient
#' @param non_num vector of equal length to ids with the number of non-icu
#'  movements for each patient
#' @param end_loc vector of equal length to ids, indicating whether each
#' patient ends in the icu or non-icu
#' @return returns a data frame with one row per patient movement in the day.
#' Columns include patient id, room type (icu or non), and time block for
#' movement.
#' @export
combine_vectors <- function(x, y) {
    .Call(`_abmpack_combine_vectors`, x, y)
}

sort_cpp <- function(x) {
    .Call(`_abmpack_sort_cpp`, x)
}

get_day_mvts_cpp <- function(ids, icu_num, non_num, end_loc) {
    .Call(`_abmpack_get_day_mvts_cpp`, ids, icu_num, non_num, end_loc)
}

#' @name move_rooms_cpp_seed
#' @title Move patient rooms
#' @description Move patients from one room to another (similar to assign
#' rooms function). Designed to deal with one facility at a time.
#' @param pat_rm_type Data frame of patients and the room type they are to go to.
#' @param icu vector of number of icu rooms available at each hospital
#' @param non vector of number of non-icu rooms available at each hospital
#' @param seed seed to be passed in to rcpp
#' @return returns data frame with one column for patient and a second column
#' for the room number to which they are assigned.
#' @export
move_rooms_cpp_seed <- function(pat_rm_type, icu, non, seed) {
    .Call(`_abmpack_move_rooms_cpp_seed`, pat_rm_type, icu, non, seed)
}

#' @name num_in_q_by_risk
#' @title Adjust admit patient list for the number of patients going to the queue.
#' @description Check how many patients from each facility need to go to the queue.
#' @param risks_beds Data frame with columns: hospital id, number of patients
#' at each risk level 1-4, number of icu beds, number of non-icu beds.
#' @return List with length equal to the number of facilities with the new
#' number of patients at each risk level after sending the proper number of patients
#' to the queue.
#' @export
adjust_for_queue <- function(num_pat, q_n) {
    .Call(`_abmpack_adjust_for_queue`, num_pat, q_n)
}

num_in_q_by_risk <- function(risks_beds) {
    .Call(`_abmpack_num_in_q_by_risk`, risks_beds)
}

#' @name sample_day_mvts_cpp_seed
#' @title Determine number of patient mvts for the day.
#' @description function to randomly sample patient daily movement patterns
#' @param los Vector of patient los for the visit,
#' @param cur_room_type vector of patients' current room type (icu/non).
#' @param seed value of seed to be passed into the rcpp.
#' @return returns character vector with the number of "icu,non" movements
#' @export
#' for the patients' upcoming day.
sample_day_mvts_cpp_seed <- function(los, cur_room_type, seed) {
    .Call(`_abmpack_sample_day_mvts_cpp_seed`, los, cur_room_type, seed)
}

