# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adjust_for_queue_l <- function(patients, q_vec) {
    .Call('_abmpack_adjust_for_queue_l', PACKAGE = 'abmpack', patients, q_vec)
}

adjust_for_queue <- function(num_pat, q_n) {
    .Call('_abmpack_adjust_for_queue', PACKAGE = 'abmpack', num_pat, q_n)
}

assign_rooms_cpp_seed <- function(pat_risks, icu, non, seed) {
    .Call('_abmpack_assign_rooms_cpp_seed', PACKAGE = 'abmpack', pat_risks, icu, non, seed)
}

combine_vectors <- function(x, y) {
    .Call('_abmpack_combine_vectors', PACKAGE = 'abmpack', x, y)
}

sort_cpp <- function(x) {
    .Call('_abmpack_sort_cpp', PACKAGE = 'abmpack', x)
}

get_day_mvts_cpp <- function(ids, icu_num, non_num, end_loc) {
    .Call('_abmpack_get_day_mvts_cpp', PACKAGE = 'abmpack', ids, icu_num, non_num, end_loc)
}

move_rooms_cpp_seed <- function(pat_rm_type, icu, non, seed) {
    .Call('_abmpack_move_rooms_cpp_seed', PACKAGE = 'abmpack', pat_rm_type, icu, non, seed)
}

adjust_for_queue <- function(num_pat, q_n) {
    .Call('_abmpack_adjust_for_queue', PACKAGE = 'abmpack', num_pat, q_n)
}

sub_vec <- function(vec_1, vec_2) {
    .Call('_abmpack_sub_vec', PACKAGE = 'abmpack', vec_1, vec_2)
}

num_in_q_by_risk <- function(risks_beds) {
    .Call('_abmpack_num_in_q_by_risk', PACKAGE = 'abmpack', risks_beds)
}

sample_day_mvts_cpp_seed <- function(los, cur_room_type, seed) {
    .Call('_abmpack_sample_day_mvts_cpp_seed', PACKAGE = 'abmpack', los, cur_room_type, seed)
}

